exports.plugin = {
    	name: 'Craigslist Categories',	
		description: 'Various categories from craigslist.org',
		options: { },
        version: '1.0',
        author: 'http://netention.org',
		start: function(netention) { 
            var t = [];
            
            netention.addTags( [{ 
                uri: 'craigslist', name: 'Craigslist'
            }] );
            
            for (var k in cldata.categories) {
                var c = cldata.categories[k];
                t.push( {
            		uri: 'craigslist.' + k,
            		name: k
            	});
            }
            
            netention.addTags(t, ['craigslist'] );
            
        },
		stop: function(netention) { }
};


var cltags = { };
cltags.Community = [
	 'activities'
	,'artists'
	,'childcare'
	,'general'
	,'groups'
	,'pets'
	,'events'
	,'lost+found'
	,'musicians'
	,'local news'
	,'politics'
	,'rideshare'
	,'volunteers'
	,'classes' 
];
cltags.Personals = [
	'strictly platonic'
	,'women seek women'
	,'women seeking men'
	,'men seeking women'
	,'men seeking men'
	,'misc romance'
	,'casual encounters'
	,'missed connections'
	,'rants and raves'
];

var cldata = {
    "categories": {
        "jobs": "jjj",
        "jewelry": "jwl",
        "video gaming": "vgm",
        "brk": "brk",
        "rooms / shared": "roo",
        "politics": "pol",
        "free": "zip",
        "toys+games": "tag",
        "baby+kids": "bab",
        "materials": "mat",
        "event": "evg",
        "skilled trade / craft": "trd",
        "activities": "act",
        "food / bev / hosp": "fbh",
        "government": "gov",
        "eby": "eby",
        "groups": "grp",
        "legal / paralegal": "lgl",
        "brx": "brx",
        "books": "bks",
        "services": "bbb",
        "real estate for sale": "rea",
        "creative": "crg",
        "housing": "hhh",
        "music instr": "msg",
        "wch": "wch",
        "systems / network": "sad",
        "rideshare": "rid",
        "arts+crafts": "art",
        "nonprofit sector": "npo",
        "arch / engineering": "egr",
        "sm biz ads": "biz",
        "beauty+hlth": "hab",
        "collectibles": "clt",
        "lgi": "lgi",
        "cds/dvd/vhs": "emd",
        "clothes+acc": "clo",
        "photo+video": "pho",
        "gigs": "ggg",
        "retail / wholesale": "ret",
        "computer": "cpg",
        "web / info design": "web",
        "crew": "cwg",
        "talent": "tlg",
        "write/ed/tr8": "wet",
        "housing swap": "swp",
        "wanted": "wan",
        "local news": "vnn",
        "lost+found": "laf",
        "motorcycles": "mca",
        "art / media / design": "med",
        "apts / housing": "apa",
        "transport": "trp",
        "business / mgmt": "bus",
        "accounting+finance": "acc",
        "internet engineers": "eng",
        "sublets / temporary": "sub",
        "rvs": "rva",
        "customer service": "csr",
        "pen": "pen",
        "labor": "lbg",
        "artists": "ats",
        "musicians": "muc",
        "pet": "pas",
        "real estate": "rej",
        "marketing / pr / ad": "mar",
        "medical / health": "hea",
        "manufacturing": "mnu",
        "for sale": "sss",
        "general labor": "lab",
        "[ETC]": "etc",
        "sporting": "spo",
        "admin / office": "ofc",
        "scz": "scz",
        "furniture": "fua",
        "automotive": "aos",
        "tv / film / video": "tfr",
        "tools": "tls",
        "bikes": "bik",
        "farm+garden": "fgs",
        "garage sale": "gms",
        "pets": "pet",
        "nby": "nby",
        "software / qa / dba": "sof",
        "tickets": "tia",
        "financial": "fns",
        "cycle": "cys",
        "household": "hss",
        "sby": "sby",
        "stn": "stn",
        "skill'd trade": "sks",
        "travel/vac": "trv",
        "office / commercial": "off",
        "housing wanted": "hsw",
        "auto parts": "pta",
        "jsy": "jsy",
        "writing / editing": "wri",
        "legal": "lgs",
        "salon / spa / fitness": "spa",
        "labor/move": "lbs",
        "therapeutic": "thp",
        "cell phones": "moa",
        "writing": "wrg",
        "security": "sec",
        "beauty": "bts",
        "education": "edu",
        "business": "bfs",
        "barter": "bar",
        "sales / biz dev": "sls",
        "human resources": "hum",
        "sfc": "sfc",
        "vacation rentals": "vac",
        "biotech / science": "sci",
        "que": "que",
        "parking / storage": "prk",
        "antiques": "atq",
        "mnh": "mnh",
        "marine": "mas",
        "lessons": "lss",
        "technical support": "tch",
        "boats": "boo",
        "volunteers": "vol",
        "community": "ccc",
        "resumes": "res",
        "domestic": "dmg",
        "fct": "fct",
        "general": "for",
        "childcare": "kid",
        "appliances": "ppa",
        "electronics": "ela"
    },
    "class": "automenta.netention.craigslist.Craigslist",
    "locations": {
        "panama city, FL": "http://panamacity.craigslist.org",
        "siskiyou county": "http://siskiyou.craigslist.org",
        "champaign urbana": "http://chambana.craigslist.org",
        "twin falls": "http://twinfalls.craigslist.org",
        "el salvador": "http://geo.craigslist.org/iso/sv",
        "sarasota-bradenton": "http://sarasota.craigslist.org",
        "tuscaloosa": "http://tuscaloosa.craigslist.org",
        "indonesia": "http://geo.craigslist.org/iso/id",
        "florida": "http://geo.craigslist.org/iso/us/fl",
        "sf bayarea": "http://sfbay.craigslist.org",
        "el paso": "http://elpaso.craigslist.org",
        "central michigan": "http://centralmich.craigslist.org",
        "nashville": "http://nashville.craigslist.org",
        "ogden-clearfield": "http://ogden.craigslist.org",
        "los angeles": "http://losangeles.craigslist.org",
        "harrisonburg": "http://harrisonburg.craigslist.org",
        "akron / canton": "http://akroncanton.craigslist.org",
        "pullman / moscow": "http://pullman.craigslist.org",
        "fargo / moorhead": "http://fargo.craigslist.org",
        "bloomington, IN": "http://bloomington.craigslist.org",
        "finger lakes": "http://fingerlakes.craigslist.org",
        "rockford": "http://rockford.craigslist.org",
        "port huron": "http://porthuron.craigslist.org",
        "portland": "http://portland.craigslist.org",
        "sandusky": "http://sandusky.craigslist.org",
        "dallas / fort worth": "http://dallas.craigslist.org",
        "outer banks": "http://outerbanks.craigslist.org",
        "the thumb": "http://thumb.craigslist.org",
        "eastern NC": "http://eastnc.craigslist.org",
        "northwest KS": "http://nwks.craigslist.org",
        "san diego": "http://sandiego.craigslist.org",
        "southeast IA": "http://ottumwa.craigslist.org",
        "la crosse": "http://lacrosse.craigslist.org",
        "louisville": "http://louisville.craigslist.org",
        "nebraska": "http://geo.craigslist.org/iso/us/ne",
        "southwest VA": "http://swva.craigslist.org",
        "austin": "http://austin.craigslist.org",
        "wisconsin": "http://geo.craigslist.org/iso/us/wi",
        "huntington-ashland": "http://huntington.craigslist.org",
        "appleton-oshkosh-FDL": "http://appleton.craigslist.org",
        "new orleans": "http://neworleans.craigslist.org",
        "plattsburgh-adirondacks": "http://plattsburgh.craigslist.org",
        "huntsville / decatur": "http://huntsville.craigslist.org",
        "inland empire": "http://inlandempire.craigslist.org",
        "hartford": "http://hartford.craigslist.org",
        "mattoon-charleston": "http://mattoon.craigslist.org",
        "hampton roads": "http://norfolk.craigslist.org",
        "imperial county": "http://imperial.craigslist.org",
        "brownsville": "http://brownsville.craigslist.org",
        "idaho": "http://geo.craigslist.org/iso/us/id",
        "bangladesh": "http://geo.craigslist.org/iso/bd",
        "seattle": "http://seattle.craigslist.org",
        "minneapolis": "http://minneapolis.craigslist.org",
        "cincinnati, OH": "http://cincinnati.craigslist.org",
        "scottsbluff / panhandle": "http://scottsbluff.craigslist.org",
        "portland, OR": "http://portland.craigslist.org",
        "texoma": "http://texoma.craigslist.org",
        "gold country": "http://goldcountry.craigslist.org",
        "macon / warner robins": "http://macon.craigslist.org",
        "salina": "http://salina.craigslist.org",
        "southwest TX": "http://bigbend.craigslist.org",
        "lawrence": "http://lawrence.craigslist.org",
        "southeast KS": "http://seks.craigslist.org",
        "hungary": "http://geo.craigslist.org/iso/hu",
        "tampa bay area": "http://tampa.craigslist.org",
        "memphis, TN": "http://memphis.craigslist.org",
        "lincoln": "http://lincoln.craigslist.org",
        "montgomery": "http://montgomery.craigslist.org",
        "louisiana": "http://geo.craigslist.org/iso/us/la",
        "grand island": "http://grandisland.craigslist.org",
        "lehigh valley": "http://allentown.craigslist.org",
        "kirksville": "http://kirksville.craigslist.org",
        "new hampshire": "http://nh.craigslist.org",
        "brazil": "http://rio.craigslist.org",
        "fort collins / north CO": "http://fortcollins.craigslist.org",
        "parkersburg-marietta": "http://parkersburg.craigslist.org",
        "grand rapids": "http://grandrapids.craigslist.org",
        "humboldt": "http://humboldt.craigslist.org",
        "hilton head": "http://hiltonhead.craigslist.org",
        "monroe": "http://monroemi.craigslist.org",
        "san luis obispo": "http://slo.craigslist.org",
        "williamsport": "http://williamsport.craigslist.org",
        "san antonio": "http://sanantonio.craigslist.org",
        "sioux falls / SE SD": "http://siouxfalls.craigslist.org",
        "jackson, TN": "http://jacksontn.craigslist.org",
        "morocco": "http://geo.craigslist.org/iso/ma",
        "roanoke": "http://roanoke.craigslist.org",
        "salt lake city": "http://saltlakecity.craigslist.org",
        "cleveland": "http://cleveland.craigslist.org",
        "gulfport / biloxi": "http://gulfport.craigslist.org",
        "venezuela": "http://geo.craigslist.org/iso/ve",
        "butte": "http://butte.craigslist.org",
        "peoria": "http://peoria.craigslist.org",
        "southwest michigan": "http://swmi.craigslist.org",
        "ithaca": "http://ithaca.craigslist.org",
        "savannah / hinesville": "http://savannah.craigslist.org",
        "wichita": "http://wichita.craigslist.org",
        "dc": "http://geo.craigslist.org/iso/us/dc",
        "prescott": "http://prescott.craigslist.org",
        "georgia": "http://geo.craigslist.org/iso/us/ga",
        "lima / findlay": "http://limaohio.craigslist.org",
        "missoula": "http://missoula.craigslist.org",
        "united states": "http://geo.craigslist.org/iso/us",
        "mississippi": "http://geo.craigslist.org/iso/us/ms",
        "los angeles": "http://losangeles.craigslist.org",
        "jacksonville": "http://jacksonville.craigslist.org",
        "provo / orem": "http://provo.craigslist.org",
        "northwest GA": "http://nwga.craigslist.org",
        "pittsburgh": "http://pittsburgh.craigslist.org",
        "joplin": "http://joplin.craigslist.org",
        "kennewick-pasco-richland": "http://kpr.craigslist.org",
        "flagstaff / sedona": "http://flagstaff.craigslist.org",
        "mobile": "http://mobile.craigslist.org",
        "evansville": "http://evansville.craigslist.org",
        "lewiston / clarkston": "http://lewiston.craigslist.org",
        "sf bay area": "http://sfbay.craigslist.org",
        "texas": "http://geo.craigslist.org/iso/us/tx",
        "lafayette": "http://lafayette.craigslist.org",
        "lubbock": "http://lubbock.craigslist.org",
        "odessa / midland": "http://odessa.craigslist.org",
        "olympic peninsula": "http://olympic.craigslist.org",
        "argentina": "http://geo.craigslist.org/iso/ar",
        "omaha / council bluffs": "http://omaha.craigslist.org",
        "costa rica": "http://geo.craigslist.org/iso/cr",
        "medford-ashland": "http://medford.craigslist.org",
        "san marcos": "http://sanmarcos.craigslist.org",
        "phoenix": "http://phoenix.craigslist.org",
        "hawaii": "http://geo.craigslist.org/iso/us/hi",
        "athens, GA": "http://athensga.craigslist.org",
        "new york": "http://newyork.craigslist.org",
        "show low": "http://showlow.craigslist.org",
        "dom republic": "http://geo.craigslist.org/iso/do",
        "houston": "http://houston.craigslist.org",
        "las vegas": "http://lasvegas.craigslist.org",
        "ukraine": "http://geo.craigslist.org/iso/ua",
        "connecticut": "http://geo.craigslist.org/iso/us/ct",
        "uae": "http://geo.craigslist.org/iso/ae",
        "holland": "http://holland.craigslist.org",
        "southeast missouri": "http://semo.craigslist.org",
        "ireland": "http://geo.craigslist.org/iso/ie",
        "little rock": "http://littlerock.craigslist.org",
        "sacramento": "http://sacramento.craigslist.org",
        "jersey shore": "http://jerseyshore.craigslist.org",
        "thailand": "http://geo.craigslist.org/iso/th",
        "fort smith, AR": "http://fortsmith.craigslist.org",
        "central nj": "http://cnj.craigslist.org",
        "southern illinois": "http://carbondale.craigslist.org",
        "oneonta": "http://oneonta.craigslist.org",
        "minnesota": "http://geo.craigslist.org/iso/us/mn",
        "western massachusetts": "http://westernmass.craigslist.org",
        "tuscarawas co": "http://tuscarawas.craigslist.org",
        "lancaster": "http://lancaster.craigslist.org",
        "iowa": "http://geo.craigslist.org/iso/us/ia",
        "annapolis": "http://annapolis.craigslist.org",
        "monterey": "http://monterey.craigslist.org",
        "knoxville": "http://knoxville.craigslist.org",
        "richmond": "http://richmond.craigslist.org",
        "ventura county": "http://ventura.craigslist.org",
        "kenai peninsula": "http://kenai.craigslist.org",
        "new jersey": "http://geo.craigslist.org/iso/us/nj",
        "iceland": "http://geo.craigslist.org/iso/is",
        "colorado springs": "http://cosprings.craigslist.org",
        "northern WI": "http://northernwi.craigslist.org",
        "orange county": "http://orangecounty.craigslist.org",
        "rhode island": "http://geo.craigslist.org/iso/us/ri",
        "nevada": "http://geo.craigslist.org/iso/us/nv",
        "las vegas": "http://lasvegas.craigslist.org",
        "bolivia": "http://geo.craigslist.org/iso/bo",
        "south korea": "http://geo.craigslist.org/iso/kr",
        "indiana": "http://geo.craigslist.org/iso/us/in",
        "winchester": "http://winchester.craigslist.org",
        "elko": "http://elko.craigslist.org",
        "clarksville, TN": "http://clarksville.craigslist.org",
        "scranton / wilkes-barre": "http://scranton.craigslist.org",
        "fort wayne": "http://fortwayne.craigslist.org",
        "corvallis/albany": "http://corvallis.craigslist.org",
        "greensboro": "http://greensboro.craigslist.org",
        "hudson valley": "http://hudsonvalley.craigslist.org",
        "albuquerque": "http://albuquerque.craigslist.org",
        "tucson": "http://tucson.craigslist.org",
        "mansfield": "http://mansfield.craigslist.org",
        "bulgaria": "http://geo.craigslist.org/iso/bg",
        "charlottesville": "http://charlottesville.craigslist.org",
        "catskills": "http://catskills.craigslist.org",
        "daytona beach": "http://daytona.craigslist.org",
        "vietnam": "http://geo.craigslist.org/iso/vn",
        "springfield, IL": "http://springfieldil.craigslist.org",
        "deep east texas": "http://nacogdoches.craigslist.org",
        "luxembourg": "http://geo.craigslist.org/iso/lu",
        "erie, PA": "http://erie.craigslist.org",
        "fayetteville": "http://fayetteville.craigslist.org",
        "meridian": "http://meridian.craigslist.org",
        "kansas": "http://geo.craigslist.org/iso/us/ks",
        "decatur, IL": "http://decatur.craigslist.org",
        "auburn": "http://auburn.craigslist.org",
        "wyoming": "http://geo.craigslist.org/iso/us/wy",
        "south coast": "http://southcoast.craigslist.org",
        "iowa city": "http://iowacity.craigslist.org",
        "atlanta": "http://atlanta.craigslist.org",
        "kenosha-racine": "http://racine.craigslist.org",
        "wilmington, NC": "http://wilmington.craigslist.org",
        "kalamazoo": "http://kalamazoo.craigslist.org",
        "janesville": "http://janesville.craigslist.org",
        "stockton": "http://stockton.craigslist.org",
        "cumberland valley": "http://chambersburg.craigslist.org",
        "green bay": "http://greenbay.craigslist.org",
        "rochester, NY": "http://rochester.craigslist.org",
        "laredo": "http://laredo.craigslist.org",
        "flint": "http://flint.craigslist.org",
        "monroe, LA": "http://monroe.craigslist.org",
        "northern panhandle": "http://wheeling.craigslist.org",
        "washington, DC": "http://washingtondc.craigslist.org",
        "north central FL": "http://lakecity.craigslist.org",
        "lakeland": "http://lakeland.craigslist.org",
        "hattiesburg": "http://hattiesburg.craigslist.org",
        "jacksonville, NC": "http://onslow.craigslist.org",
        "northwest OK": "http://enid.craigslist.org",
        "greenville / upstate": "http://greenville.craigslist.org",
        "battle creek": "http://battlecreek.craigslist.org",
        "malaysia": "http://geo.craigslist.org/iso/my",
        "mendocino co": "http://mendocino.craigslist.org",
        "san angelo": "http://sanangelo.craigslist.org",
        "redding": "http://redding.craigslist.org",
        "montana (old)": "http://montana.craigslist.org",
        "kansas city, MO": "http://kansascity.craigslist.org",
        "albany, GA": "http://albanyga.craigslist.org",
        "detroit metro": "http://detroit.craigslist.org",
        "hanford-corcoran": "http://hanford.craigslist.org",
        "puerto rico": "http://geo.craigslist.org/iso/pr",
        "allentown": "http://allentown.craigslist.org",
        "orange co": "http://orangecounty.craigslist.org",
        "las cruces": "http://lascruces.craigslist.org",
        "south dakota": "http://geo.craigslist.org/iso/us/sd",
        "alabama": "http://geo.craigslist.org/iso/us/al",
        "columbia / jeff city": "http://columbiamo.craigslist.org",
        "mankato": "http://mankato.craigslist.org",
        "anchorage / mat-su": "http://anchorage.craigslist.org",
        "spokane / coeur d'alene": "http://spokane.craigslist.org",
        "central NJ": "http://cnj.craigslist.org",
        "western slope": "http://westslope.craigslist.org",
        "waco": "http://waco.craigslist.org",
        "southern maryland": "http://smd.craigslist.org",
        "killeen / temple / ft hood": "http://killeen.craigslist.org",
        "del rio / eagle pass": "http://delrio.craigslist.org",
        "des moines": "http://desmoines.craigslist.org",
        "farmington, NM": "http://farmington.craigslist.org",
        "iran": "http://geo.craigslist.org/iso/ir",
        "springfield, MO": "http://springfield.craigslist.org",
        "oklahoma city": "http://oklahomacity.craigslist.org",
        "sioux city, IA": "http://siouxcity.craigslist.org",
        "maine": "http://geo.craigslist.org/iso/us/me",
        "west virginia": "http://geo.craigslist.org/iso/us/wv",
        "rochester, MN": "http://rmn.craigslist.org",
        "colorado": "http://geo.craigslist.org/iso/us/co",
        "lake charles": "http://lakecharles.craigslist.org",
        "kokomo": "http://kokomo.craigslist.org",
        "new york": "http://geo.craigslist.org/iso/us/ny",
        "cape cod / islands": "http://capecod.craigslist.org",
        "iraq": "http://geo.craigslist.org/iso/iq",
        "netherlands": "http://geo.craigslist.org/iso/nl",
        "ft myers / SW florida": "http://fortmyers.craigslist.org",
        "myrtle beach": "http://myrtlebeach.craigslist.org",
        "panama": "http://geo.craigslist.org/iso/pa",
        "missouri": "http://geo.craigslist.org/iso/us/mo",
        "bismarck": "http://bismarck.craigslist.org",
        "asheville": "http://asheville.craigslist.org",
        "texarkana": "http://texarkana.craigslist.org",
        "lake of the ozarks": "http://loz.craigslist.org",
        "fresno": "http://fresno.craigslist.org",
        "tri-cities, TN": "http://tricities.craigslist.org",
        "billings": "http://billings.craigslist.org",
        "albany": "http://albany.craigslist.org",
        "fayetteville, AR": "http://fayar.craigslist.org",
        "binghamton": "http://binghamton.craigslist.org",
        "romania": "http://geo.craigslist.org/iso/ro",
        "manhattan, KS": "http://ksu.craigslist.org",
        "klamath falls": "http://klamath.craigslist.org",
        "pakistan": "http://geo.craigslist.org/iso/pk",
        "washington": "http://geo.craigslist.org/iso/us/wa",
        "jonesboro": "http://jonesboro.craigslist.org",
        "ames, IA": "http://ames.craigslist.org",
        "virginia": "http://geo.craigslist.org/iso/us/va",
        "western maryland": "http://westmd.craigslist.org",
        "birmingham, AL": "http://bham.craigslist.org",
        "chattanooga": "http://chattanooga.craigslist.org",
        "west bank": "http://geo.craigslist.org/iso/ps",
        "victoria, TX": "http://victoriatx.craigslist.org",
        "wash dc": "http://washingtondc.craigslist.org",
        "yakima": "http://yakima.craigslist.org",
        "california": "http://geo.craigslist.org/iso/us/ca",
        "miami": "http://miami.craigslist.org",
        "croatia": "http://geo.craigslist.org/iso/hr",
        "lebanon": "http://geo.craigslist.org/iso/lb",
        "columbus, GA": "http://columbusga.craigslist.org",
        "st augustine": "http://staugustine.craigslist.org",
        "chautauqua": "http://chautauqua.craigslist.org",
        "brunswick, GA": "http://brunswick.craigslist.org",
        "mason city": "http://masoncity.craigslist.org",
        "sheboygan, WI": "http://sheboygan.craigslist.org",
        "owensboro": "http://owensboro.craigslist.org",
        "oklahoma": "http://geo.craigslist.org/iso/us/ok",
        "bloomington-normal": "http://bn.craigslist.org",
        "monterey bay": "http://monterey.craigslist.org",
        "beaumont / port arthur": "http://beaumont.craigslist.org",
        "amarillo": "http://amarillo.craigslist.org",
        "pierre / central SD": "http://csd.craigslist.org",
        "arizona": "http://geo.craigslist.org/iso/us/az",
        "glens falls": "http://glensfalls.craigslist.org",
        "clovis / portales": "http://clovis.craigslist.org",
        "denver": "http://denver.craigslist.org",
        "uruguay": "http://geo.craigslist.org/iso/uy",
        "houma": "http://houma.craigslist.org",
        "elmira-corning": "http://elmira.craigslist.org",
        "buffalo": "http://buffalo.craigslist.org",
        "moses lake": "http://moseslake.craigslist.org",
        "danville": "http://danville.craigslist.org",
        "poconos": "http://poconos.craigslist.org",
        "tennessee": "http://geo.craigslist.org/iso/us/tn",
        "pennsylvania": "http://geo.craigslist.org/iso/us/pa",
        "philadelphia": "http://philadelphia.craigslist.org",
        "santa maria": "http://santamaria.craigslist.org",
        "new zealand": "http://auckland.craigslist.org",
        "bemidji": "http://bemidji.craigslist.org",
        "michigan": "http://geo.craigslist.org/iso/us/mi",
        "s carolina": "http://geo.craigslist.org/iso/us/sc",
        "winston-salem": "http://winstonsalem.craigslist.org",
        "space coast": "http://spacecoast.craigslist.org",
        "roseburg": "http://roseburg.craigslist.org",
        "grand forks": "http://grandforks.craigslist.org",
        "fairbanks": "http://fairbanks.craigslist.org",
        "boone": "http://boone.craigslist.org",
        "long island": "http://longisland.craigslist.org",
        "duluth / superior": "http://duluth.craigslist.org",
        "state college": "http://pennstate.craigslist.org",
        "new york city": "http://newyork.craigslist.org",
        "vermont": "http://geo.craigslist.org/iso/us/vt",
        "oregon": "http://geo.craigslist.org/iso/us/or",
        "richmond, IN": "http://richmondin.craigslist.org",
        "st cloud": "http://stcloud.craigslist.org",
        "bend": "http://bend.craigslist.org",
        "baltimore": "http://baltimore.craigslist.org",
        "zanesville / cambridge": "http://zanesville.craigslist.org",
        "new river valley": "http://blacksburg.craigslist.org",
        "ghana": "http://geo.craigslist.org/iso/gh",
        "eastern ct": "http://newlondon.craigslist.org",
        "ann arbor": "http://annarbor.craigslist.org",
        "orlando": "http://orlando.craigslist.org",
        "charlotte": "http://charlotte.craigslist.org",
        "chicago": "http://chicago.craigslist.org",
        "meadville": "http://meadville.craigslist.org",
        "new haven": "http://newhaven.craigslist.org",
        "hanford": "http://hanford.craigslist.org",
        "saginaw-midland-baycity": "http://saginaw.craigslist.org",
        "valdosta": "http://valdosta.craigslist.org",
        "eugene": "http://eugene.craigslist.org",
        "n hampshire": "http://geo.craigslist.org/iso/us/nh",
        "youngstown": "http://youngstown.craigslist.org",
        "cedar rapids": "http://cedarrapids.craigslist.org",
        "seattle-tacoma": "http://seattle.craigslist.org",
        "frederick": "http://frederick.craigslist.org",
        "western IL": "http://quincy.craigslist.org",
        "madison": "http://madison.craigslist.org",
        "ethiopia": "http://geo.craigslist.org/iso/et",
        "okaloosa / walton": "http://okaloosa.craigslist.org",
        "potsdam-canton-massena": "http://potsdam.craigslist.org",
        "pensacola": "http://pensacola.craigslist.org",
        "altoona-johnstown": "http://altoona.craigslist.org",
        "dayton / springfield": "http://dayton.craigslist.org",
        "augusta": "http://augusta.craigslist.org",
        "czech republic": "http://geo.craigslist.org/iso/cz",
        "east idaho": "http://eastidaho.craigslist.org",
        "tallahassee": "http://tallahassee.craigslist.org",
        "illinois": "http://geo.craigslist.org/iso/us/il",
        "high rockies": "http://rockies.craigslist.org",
        "north mississippi": "http://northmiss.craigslist.org",
        "eastern shore": "http://easternshore.craigslist.org",
        "us virgin islands": "http://geo.craigslist.org/iso/vi",
        "lawton": "http://lawton.craigslist.org",
        "west virginia (old)": "http://wv.craigslist.org",
        "cookeville": "http://cookeville.craigslist.org",
        "dubuque": "http://dubuque.craigslist.org",
        "shreveport": "http://shreveport.craigslist.org",
        "chile": "http://geo.craigslist.org/iso/cl",
        "great falls": "http://greatfalls.craigslist.org",
        "south jersey": "http://southjersey.craigslist.org",
        "guam": "http://geo.craigslist.org/iso/gu",
        "harrisburg": "http://harrisburg.craigslist.org",
        "western mass": "http://westernmass.craigslist.org",
        "eastern CT": "http://newlondon.craigslist.org",
        "north jersey": "http://newjersey.craigslist.org",
        "quad cities, IA/IL": "http://quadcities.craigslist.org",
        "eastern CO": "http://eastco.craigslist.org",
        "western KY": "http://westky.craigslist.org",
        "wausau": "http://wausau.craigslist.org",
        "muncie / anderson": "http://muncie.craigslist.org",
        "la salle co": "http://lasalle.craigslist.org",
        "college station": "http://collegestation.craigslist.org",
        "north dakota": "http://geo.craigslist.org/iso/us/nd",
        "northern michigan": "http://nmi.craigslist.org",
        "ocala": "http://ocala.craigslist.org",
        "humboldt county": "http://humboldt.craigslist.org",
        "muskegon": "http://muskegon.craigslist.org",
        "yuba-sutter": "http://yubasutter.craigslist.org",
        "dothan, AL": "http://dothan.craigslist.org",
        "bozeman": "http://bozeman.craigslist.org",
        "syracuse": "http://syracuse.craigslist.org",
        "tunisia": "http://geo.craigslist.org/iso/tn",
        "heartland florida": "http://cfl.craigslist.org",
        "san diego": "http://sandiego.craigslist.org",
        "york, PA": "http://york.craigslist.org",
        "treasure coast": "http://treasure.craigslist.org",
        "salem, OR": "http://salem.craigslist.org",
        "southwest KS": "http://swks.craigslist.org",
        "florida keys": "http://keys.craigslist.org",
        "bowling green": "http://bgky.craigslist.org",
        "abilene": "http://abilene.craigslist.org",
        "mohave county": "http://mohave.craigslist.org",
        "lafayette / west lafayette": "http://tippecanoe.craigslist.org",
        "northwest ct": "http://nwct.craigslist.org",
        "corpus christi": "http://corpuschristi.craigslist.org",
        "toledo": "http://toledo.craigslist.org",
        "sierra vista": "http://sierravista.craigslist.org",
        "charleston, SC": "http://charleston.craigslist.org",
        "morgantown": "http://morgantown.craigslist.org",
        "galveston": "http://galveston.craigslist.org",
        "fredericksburg": "http://fredericksburg.craigslist.org",
        "florence / muscle shoals": "http://shoals.craigslist.org",
        "arkansas": "http://geo.craigslist.org/iso/us/ar",
        "n carolina": "http://geo.craigslist.org/iso/us/nc",
        "boise": "http://boise.craigslist.org",
        "fort dodge": "http://fortdodge.craigslist.org",
        "watertown": "http://watertown.craigslist.org",
        "delaware": "http://geo.craigslist.org/iso/us/de",
        "wichita falls": "http://wichitafalls.craigslist.org",
        "utica-rome-oneida": "http://utica.craigslist.org",
        "raleigh / durham / CH": "http://raleigh.craigslist.org",
        "fresno / madera": "http://fresno.craigslist.org",
        "lynchburg": "http://lynchburg.craigslist.org",
        "south florida": "http://miami.craigslist.org",
        "northeast SD": "http://nesd.craigslist.org",
        "tulsa": "http://tulsa.craigslist.org",
        "modesto": "http://modesto.craigslist.org",
        "helena": "http://helena.craigslist.org",
        "southwest MS": "http://natchez.craigslist.org",
        "dallas": "http://dallas.craigslist.org",
        "southwest MN": "http://marshall.craigslist.org",
        "boulder": "http://boulder.craigslist.org",
        "susanville": "http://susanville.craigslist.org",
        "roswell / carlsbad": "http://roswell.craigslist.org",
        "norway": "http://geo.craigslist.org/iso/no",
        "new mexico": "http://geo.craigslist.org/iso/us/nm",
        "gadsden-anniston": "http://gadsden.craigslist.org",
        "reno": "http://reno.craigslist.org",
        "ohio": "http://geo.craigslist.org/iso/us/oh",
        "boston": "http://boston.craigslist.org",
        "stillwater": "http://stillwater.craigslist.org",
        "montana": "http://geo.craigslist.org/iso/us/mt",
        "ashtabula": "http://ashtabula.craigslist.org",
        "northwest CT": "http://nwct.craigslist.org",
        "waterloo / cedar falls": "http://waterloo.craigslist.org",
        "minneapolis / st paul": "http://minneapolis.craigslist.org",
        "tyler / east TX": "http://easttexas.craigslist.org",
        "st joseph": "http://stjoseph.craigslist.org",
        "north platte": "http://northplatte.craigslist.org",
        "scranton": "http://scranton.craigslist.org",
        "southeast alaska": "http://juneau.craigslist.org",
        "visalia-tulare": "http://visalia.craigslist.org",
        "russia": "http://moscow.craigslist.org",
        "central louisiana": "http://cenla.craigslist.org",
        "utah": "http://geo.craigslist.org/iso/us/ut",
        "pueblo": "http://pueblo.craigslist.org",
        "hickory / lenoir": "http://hickory.craigslist.org",
        "brainerd": "http://brainerd.craigslist.org",
        "eastern panhandle": "http://martinsburg.craigslist.org",
        "reading": "http://reading.craigslist.org",
        "wenatchee": "http://wenatchee.craigslist.org",
        "kenya": "http://geo.craigslist.org/iso/ke",
        "terre haute": "http://terrehaute.craigslist.org",
        "statesboro": "http://statesboro.craigslist.org",
        "mass": "http://geo.craigslist.org/iso/us/ma",
        "colombia": "http://geo.craigslist.org/iso/co",
        "kalispell": "http://kalispell.craigslist.org",
        "lexington, KY": "http://lexington.craigslist.org",
        "logan": "http://logan.craigslist.org",
        "mcallen / edinburg": "http://mcallen.craigslist.org",
        "jackson, MS": "http://jackson.craigslist.org",
        "maryland": "http://geo.craigslist.org/iso/us/md",
        "jackson, MI": "http://jxn.craigslist.org",
        "east oregon": "http://eastoregon.craigslist.org",
        "mendocino county": "http://mendocino.craigslist.org",
        "charleston, WV": "http://charlestonwv.craigslist.org",
        "st louis, MO": "http://stlouis.craigslist.org",
        "ecuador": "http://geo.craigslist.org/iso/ec",
        "bellingham": "http://bellingham.craigslist.org",
        "indianapolis": "http://indianapolis.craigslist.org",
        "alaska": "http://geo.craigslist.org/iso/us/ak",
        "worcester / central MA": "http://worcester.craigslist.org",
        "chillicothe": "http://chillicothe.craigslist.org",
        "south bend / michiana": "http://southbend.craigslist.org",
        "bakersfield": "http://bakersfield.craigslist.org",
        "palm springs, CA": "http://palmsprings.craigslist.org",
        "upper peninsula": "http://up.craigslist.org",
        "florence, SC": "http://florencesc.craigslist.org",
        "twin tiers NY/PA": "http://twintiers.craigslist.org",
        "gainesville": "http://gainesville.craigslist.org",
        "columbia, SC": "http://columbia.craigslist.org",
        "oregon coast": "http://oregoncoast.craigslist.org",
        "lancaster, PA": "http://lancaster.craigslist.org",
        "baton rouge": "http://batonrouge.craigslist.org",
        "SF bay area": "http://sfbay.craigslist.org",
        "eastern kentucky": "http://eastky.craigslist.org",
        "israel": "http://telaviv.craigslist.org",
        "chico": "http://chico.craigslist.org",
        "skagit / island / SJI": "http://skagit.craigslist.org",
        "kentucky": "http://geo.craigslist.org/iso/us/ky",
        "yuma": "http://yuma.craigslist.org",
        "milwaukee": "http://milwaukee.craigslist.org",
        "st george": "http://stgeorge.craigslist.org",
        "santa barbara": "http://santabarbara.craigslist.org",
        "athens, OH": "http://athensohio.craigslist.org",
        "santa fe / taos": "http://santafe.craigslist.org",
        "topeka": "http://topeka.craigslist.org",
        "guatemala": "http://geo.craigslist.org/iso/gt",
        "southern WV": "http://swv.craigslist.org",
        "columbus": "http://columbus.craigslist.org",
        "merced": "http://merced.craigslist.org",
        "eau claire": "http://eauclaire.craigslist.org",
        "nicaragua": "http://geo.craigslist.org/iso/ni",
        "raleigh": "http://raleigh.craigslist.org",
        "egypt": "http://geo.craigslist.org/iso/eg",
        "lansing": "http://lansing.craigslist.org",
        "reno / tahoe": "http://reno.craigslist.org",
        "rapid city / west SD": "http://rapidcity.craigslist.org",
        "kuwait": "http://geo.craigslist.org/iso/kw",
        "detroit": "http://detroit.craigslist.org"
    }
};

